### ISSUE TITLE
Error during first install and set up

### ISSUE THREAD

**Issue by thm-design** [TarikHuber/react-most-wanted#1] opened 2017-06-07 22:16 UTC
Hey I ran into this error after cloning the repo and running: 
```
yarn && yarn start
```

```
./~/material-ui-responsive-drawer/es/ResponsiveAppBar.js
Module not found: Can't resolve 'material-ui-icons/Menu' in [project path]/node_modules/material-ui-responsive-drawer/es'
```

<img width="1086" alt="screen shot 2017-06-07 at 3 12 29 pm" src="https://user-images.githubusercontent.com/1038100/26903839-01ea1cc0-4b94-11e7-916d-c9f90024bc98.png">

Any idea on what I missed during set up? Do I have to run the firebase install steps in order to run the app locally with out any auth features?

Cheers.

**Comment by TarikHuber** [comment] 2017-06-07 22:26
Hi @thm-design do you have a fork or repo where I could try to reproduce the issue?
Did you change the package.json file? Have you tried to do it with npm?

**Comment by thm-design** [comment] 2017-06-07 22:35
Don't have a fork unfortunately, I just git cloned it. Then:

```
rm -rf .git
```

```
git init
```
Changed name in package.json to:

```
"name": "protoype"
``` 

```
yarn && yarn start
```

Error occured.

Just tried with npm instead of yarn, same thing happend.

OSX: 10.12.4 (Sierra)
node version: v6.9.5

**Comment by TarikHuber** [comment] 2017-06-07 22:36
Did you install the dependencies? (npm install or yarn install)

**Comment by thm-design** [comment] 2017-06-07 22:37
Yes, for yarn, the equivalent to `npm i` command is just

`yarn`

**Comment by thm-design** [comment] 2017-06-07 22:39
So I looked in the node module folder in the file in the error. (ResponsiveAppBar.js)
It is looking for `'material-ui-icons/Menu'` . if you change it to `'material-ui/Menu'` it works.
Not sure if this was a change to material-ui ?

**Comment by TarikHuber** [comment] 2017-06-07 22:49
Hmm what version of material-ui-responsive-drawer was installed in your project? There is a new @next version that is made only for material-ui@next and that doesn't support the current version 0.18.2.

This project can't use for now the MUI @next version. When it gets released or the most parts added to it I will upgrade it to the @next.

Could that be the problem? Because in the @next version the icons are moved to a seperate project.

**Comment by thm-design** [comment] 2017-06-07 22:55
No don't thing that is the problem, I was checking for that too, the version in the package.json is `"material-ui": "^0.18.2"` 

```
{
  "name": "prototype",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "enzyme": "^2.8.2",
    "highlight.js": "^9.12.0",
    "react-scripts": "^1.0.6",
    "react-test-renderer": "^15.5.4",
    "redux-logger": "^3.0.6",
    "redux-mock-store": "^1.2.3",
    "redux-testkit": "^1.0.6"
  },
  "dependencies": {
    "clientjs": "^0.1.11",
    "cuid": "^1.3.8",
    "firebase": "^4.1.1",
    "firebaseui": "^2.0.0",
    "github-markdown-css": "^2.6.0",
    "immutable": "^3.8.1",
    "intl": "^1.2.5",
    "intl-locales-supported": "^1.0.0",
    "lodash": "^4.17.4",
    "marked": "^0.3.6",
    "material-ui": "^0.18.2",
    "material-ui-responsive-drawer": "^1.1.22",
    "material-ui-selectable-menu-list": "^1.1.22",
    "material-ui-superselectfield": "^1.5.4",
    "prop-types": "^15.5.10",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-helmet": "^5.1.3",
    "react-image-cropper": "^1.1.0",
    "react-intl": "^2.3.0",
    "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.6.0",
    "redux-form": "^6.7.0",
    "redux-form-material-ui": "^4.2.0",
    "redux-persist": "^4.8.0",
    "redux-responsive": "^4.3.2",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "seamless-immutable": "^7.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom --collectCoverageFrom=src/store/**/*js --collectCoverageFrom=!src/store/*js",
    "eject": "react-scripts eject"
  }
}

```
Also just did an app wide search for `@next` only places I found are here:

![screen shot 2017-06-07 at 3 54 55 pm](https://user-images.githubusercontent.com/1038100/26905018-b7c7cc86-4b99-11e7-8e58-9e364912017d.png)

**Comment by thm-design** [comment] 2017-06-07 23:00
![screen shot 2017-06-07 at 3 59 42 pm](https://user-images.githubusercontent.com/1038100/26905141-6bf17982-4b9a-11e7-9e9e-45d9209a1493.png)

**Comment by TarikHuber** [comment] 2017-06-07 23:03
If you go to the repo of material-ui-responsive-drawer you will se that only the @next version needs that import causing this issue. That import is not present in the version that should be installed.

**Comment by thm-design** [comment] 2017-06-07 23:14
Hmm ok so what went wrong? How did I end up with code that needs the @next branch? I cloned like this `git clone git@github.com:TarikHuber/react-most-wanted.git prototype`.

I will try again later from the start see what happens.
Cheers.

**Comment by TarikHuber** [comment] 2017-06-07 23:22
It is realy strange. Could it be that yarn install the latest version and not the stable? Here you can see the stable and latest version for this repo: [Packages](https://david-dm.org/TarikHuber/react-most-wanted)

I just pushed a commit with the newest version for the material-ui-responsive-drawer with your changes merged into it :)

I would suggest to clone the project again and to try it only with npm.

**Comment by thm-design** [comment] 2017-06-07 23:52
Cloning a fresh copy and using npm worked :) 💯

**Closed** 2017-06-08 06:04 UTC
